import type {
  OHLCV,
  Signal,
  Trade,
  Position,
  BacktestResult,
  EquityPoint,
  PerformanceMetrics,
} from "@pinescript-utils/core";
import { calculateMetrics } from "@pinescript-utils/core";
import { BacktestConfig, DEFAULT_CONFIG } from "./engine.js";

/**
 * Position tracking specifically for paper trading
 * Mirrors the backtest tracker but optimized for live updates
 */
class LivePositionTracker {
  private positions: Map<string, Position> = new Map();
  private trades: Trade[] = [];
  private tradeId = 0;

  getPosition(symbol: string): Position | undefined {
    return this.positions.get(symbol);
  }

  hasPosition(symbol: string): boolean {
    return this.positions.has(symbol);
  }

  openPosition(
    symbol: string,
    direction: "long" | "short",
    price: number,
    quantity: number,
    timestamp: number,
  ): void {
    const position: Position = {
      symbol,
      direction,
      entryPrice: price,
      quantity,
      entryTime: timestamp,
      unrealizedPnl: 0,
    };
    this.positions.set(symbol, position);

    this.trades.push({
      id: `paper_trade_${this.tradeId++}`,
      timestamp,
      direction,
      action: "buy",
      price,
      quantity,
      symbol,
    });
  }

  closePositionWithPnl(
    symbol: string,
    price: number,
    timestamp: number,
    pnl: number,
  ): void {
    const position = this.positions.get(symbol);
    if (!position) return;

    this.trades.push({
      id: `paper_trade_${this.tradeId++}`,
      timestamp,
      direction: position.direction,
      action: "sell",
      price,
      quantity: position.quantity,
      symbol,
      pnl,
    });

    this.positions.delete(symbol);
  }

  updateUnrealizedPnl(symbol: string, currentPrice: number): void {
    const position = this.positions.get(symbol);
    if (!position) return;

    if (position.direction === "long") {
      position.unrealizedPnl =
        (currentPrice - position.entryPrice) * position.quantity;
    } else {
      position.unrealizedPnl =
        (position.entryPrice - currentPrice) * position.quantity;
    }
  }

  getAllPositions(): Position[] {
    return Array.from(this.positions.values());
  }

  getAllTrades(): Trade[] {
    return [...this.trades];
  }
}

export interface PaperTradeState {
  cash: number;
  equity: number;
  unrealizedPnl: number;
  positions: Position[];
  trades: Trade[];
  metrics: PerformanceMetrics | null;
  equityCurve: EquityPoint[];
}

/**
 * Engine for running strategies in real-time against live market data streams
 */
export class PaperTradeEngine {
  private config: BacktestConfig;
  private positions: LivePositionTracker;
  private cash: number;
  private equity: number;
  private peakEquity: number;
  private equityCurve: EquityPoint[] = [];
  private startTime: number;

  // Callback for UI updates when state changes
  public onStateUpdate?: (state: PaperTradeState) => void;
  public onTrade?: (trade: Trade) => void;

  constructor(config: Partial<BacktestConfig> = {}) {
    this.config = { ...DEFAULT_CONFIG, ...config };
    this.positions = new LivePositionTracker();
    this.cash = this.config.initialCapital;
    this.equity = this.config.initialCapital;
    this.peakEquity = this.config.initialCapital;
    this.startTime = Date.now();
  }

  /**
   * Process a single tick/candle update from the live feed
   */
  public async processUpdate(
    candle: OHLCV,
    newSignals: Signal[],
    symbol: string,
  ): Promise<void> {
    // Process new signals generated by this tick
    for (const signal of newSignals) {
      await this.executeSignal(signal, symbol);
    }

    // Update unrealized PnL and equity based on current price
    this.updateEquity(candle);

    // Notify listeners of new state
    this.notifyStateUpdate();
  }

  /**
   * Execute a signal at current market conditions
   */
  private async executeSignal(signal: Signal, symbol: string): Promise<void> {
    const hasPosition = this.positions.hasPosition(symbol);

    // Apply slippage
    let executionPrice = signal.price;
    if (signal.action === "buy") {
      executionPrice *= 1 + this.config.slippage;
    } else {
      executionPrice *= 1 - this.config.slippage;
    }

    if (signal.action === "buy" && !hasPosition) {
      // Open long
      const positionValue = this.cash * this.config.positionSize;
      const quantity = positionValue / executionPrice;
      const commission = positionValue * this.config.commission;

      this.cash -= positionValue + commission;
      this.positions.openPosition(
        symbol,
        "long",
        executionPrice,
        quantity,
        signal.timestamp,
      );

      this.notifyTrade(this.positions.getAllTrades().slice(-1)[0]);
    } else if (signal.action === "sell" && hasPosition) {
      // Close position
      const position = this.positions.getPosition(symbol)!;
      const positionValue = position.quantity * executionPrice;
      const commission = positionValue * this.config.commission;

      const pnl = (executionPrice - position.entryPrice) * position.quantity;

      this.positions.closePositionWithPnl(
        symbol,
        executionPrice,
        signal.timestamp,
        pnl,
      );
      this.cash += positionValue - commission;

      this.notifyTrade(this.positions.getAllTrades().slice(-1)[0]);
    }
  }

  /**
   * Update internal equity tracking
   */
  private updateEquity(candle: OHLCV): void {
    let totalEquity = this.cash;

    for (const position of this.positions.getAllPositions()) {
      this.positions.updateUnrealizedPnl(position.symbol, candle.close);
      totalEquity += position.quantity * candle.close;
    }

    this.equity = totalEquity;
    if (this.equity > this.peakEquity) {
      this.peakEquity = this.equity;
    }

    const drawdown = (this.peakEquity - this.equity) / this.peakEquity;

    this.equityCurve.push({
      timestamp: candle.timestamp,
      equity: this.equity,
      drawdown,
    });
  }

  private notifyStateUpdate(): void {
    if (this.onStateUpdate) {
      this.onStateUpdate(this.getState());
    }
  }

  private notifyTrade(trade: Trade): void {
    if (this.onTrade) {
      this.onTrade(trade);
    }
  }

  /**
   * Get current engine state
   */
  public getState(): PaperTradeState {
    const trades = this.positions.getAllTrades();
    let metrics: PerformanceMetrics | null = null;

    if (trades.length > 0 && this.equityCurve.length > 0) {
      const equityValues = this.equityCurve.map((e) => e.equity);
      // calculateMetrics throws an error if length <= 1, so only run if we have enough data points
      if (equityValues.length > 1) {
        try {
          metrics = calculateMetrics(
            trades,
            equityValues,
            this.config.initialCapital,
            this.equity,
            this.startTime,
            Date.now(),
          );
        } catch (e) {
          metrics = null;
        }
      }
    }

    return {
      cash: this.cash,
      equity: this.equity,
      unrealizedPnl: this.equity - this.config.initialCapital,
      positions: this.positions.getAllPositions(),
      trades,
      metrics,
      equityCurve: this.equityCurve,
    };
  }
}
